FROM python:3.13.9-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uv \
    && pip cache purge
WORKDIR /api
COPY pyproject.toml uv.lock .
RUN uv sync --no-dev --no-editable --frozen
COPY src/loggers.py src/processing.py src/main.py src/pydantic_models.py .
COPY src/static/ static/
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]